### ISSUE TITLE
Command pattern with side effects

### ISSUE THREAD

**Issue by steida** [gcanti/fp-ts#1005]
## 📖 Documentation

I am not sure how to implement it. Let's say we need a simple pipe transformation with side effects.

```ts
const nextValue = pipe(
  value,
  // We don't need side effect.
  select({ anchor: [0, 0, 0], focus: [0, 0, 2] }),
  // insertText needs some ad-hoc computed data from DOM via editor.
  insertText('foo')(editor),
)
```

Maybe it could be refactored into sync command aka some queue? nextValue is React editor prop value.

**Comment by DenisFrezzato** [comment]
Can you add the type signature of `insertText`?

**Comment by steida** [comment]
Let's say insertText has to use something from value to read DOM styles and by that create a new value.

**Comment by DenisFrezzato** [comment]
There are two abstractions meant for side effects: [IO](https://gcanti.github.io/fp-ts/modules/IO.ts.html) (synchronous) and [Task](https://gcanti.github.io/fp-ts/modules/Task.ts.html) (asynchronous). Both of them have the `-Either` "version" for computations that may fail.

Since you mentioned the DOM, `IO` fits your use case, so you can refactor `insertText` so that `insertText('foo')(editor)` returns a `IO<string>` (not sure about `string`, I'm guessing). In this way you end up with a referential transparent representation of a side effect, which you can fire as late as possible.

**Comment by steida** [comment]
@DenisFrezzato So it is idiomatic fp-ts to mix Option and IO in one pipe?

**Comment by DenisFrezzato** [comment]
Yeah, I don't see any problem, `pipe` just _pipes_ an argument into `n` functions, so as long as it's correct and it makes sense, it's fine.

**Comment by steida** [comment]
How would you explain the advantage of "referential transparent representation of a side effect" for a beginner? I am explaining it as "IO defers dangerous (hard or impossible to mock) execution" but I feel it's not enough.
