### ISSUE TITLE
Either requires type narrowing while TaskEither not

### ISSUE THREAD

**Issue by steida** [gcanti/fp-ts#1061]
## 🐛 Bug report

This code works:

```ts
const createToken: Create<NanoID> = () =>
  pipe(
    createNanoID(),
    TE.fromEither,
    TE.mapLeft(() => 'internalServerError'),
  );
```

But this semantically identic code does not:

```ts
//  Type 'string' is not assignable to type '{ type: "FetchError"; message: string; } | "badRequest" ...
const createToken: Create<NanoID> = () =>
  pipe(
    createNanoID(),
    E.mapLeft(() => 'internalServerError'),
    TE.fromEither,
  );
```

`as const` fixes it:

```ts
const createToken: Create<NanoID> = () =>
  pipe(
    createNanoID(),
    E.mapLeft(() => 'internalServerError' as const),
    TE.fromEither,
  );
```

As I see it, `as const` should not be required. Am I correct?

```ts
type Create<T> = (
  input: Mutation['input'],
) => TE.TaskEither<Mutation['error'], T>;
```

**Comment by gcanti** [comment]
@steida please follow the issue template and/or file a reproducible example.

At a first glance this is not a bug, in the first case TypeScript is able to infer the expected type because `mapLeft` is in last position in the `pipe`line (if you add one more element, say `identity`, shouldn't type check anymore)

**Comment by steida** [comment]
@gcanti Thank you.
