### ISSUE TITLE
How do I use Map's lookup function in a pipe?

### ISSUE THREAD

**Issue by Melvillian** [gcanti/fp-ts#1160]
## 📖 Documentation

warning I am an FP noob, but trying!

I am trying to make use of the builtin `Map` and see if a value exists, however I cannot glean how to do it from the `fp-ts` documentation.

So far I have

```
get_child(s: string): Option<Node> {
        return pipe(
            this.children,
            getOrElse(() => new Map<string, Node>()),
            lookup(Eq)(s)
        );
    }
```

where `s` is a key within the `children` Map<string, Node> (it's not important what type `Node` is. However it's complaining that I need to pass 2 args instead of 1. I see `lookup`'s function signature takes a `Map` as the second parameter... but this doesn't make sense to me if I'm supposed to be doing things in a non-imperative, functional manner and thus use `pipe`.

as an aside I'd like to echo https://github.com/gcanti/fp-ts/issues/1076 where more examples would be much appreciated for beginners. If you'd add some basic examples for https://gcanti.github.io/fp-ts/modules/Map.ts.html and https://gcanti.github.io/fp-ts/modules/Array.ts.html I'd be happy to add a PR fleshing out examples for the rest of Map and Array's functions so future beginners would know what to do.

**Comment by newswim** [comment]
Hi @Melvillian, a couple things to note in your question:

1. Functions like `lookup` and `getOrElse` are specific to the module where they're exported from.
  - `Option`'s lookup is different from `Map`'s lookup function.

2. You were right that Map's lookup does take an Eq as its first argument, however it needs an Eq _instance_, eg. `eqString`, `eqBoolean`. `Eq` represents the class, and lookup would not know which eq to use. There are ways up deriving an `Eq` for Options via `getEq`, but in this case you're using a string. Here's a working example that might help:

```ts
import * as M from 'fp-ts/lib/Map'
import { eqString } from 'fp-ts/lib/Eq'

const m: Map<string, string> = new Map()

m.set('foo', 'bar')

M.lookup(eqString)('foo', m) // { _tag: 'Some', value: 'bar' } 
```

3. I don't think this pattern lends itself well to `pipe` because lookup is not curried. You could go and make a curried version if you wanted to, but I think in this small example you may be better off forgoing `pipe`.

Here's an illustration of using pipe, where you can also see why lookup not being curried makes the result a bit awkward:

```ts
const pipeExample = pipe(m, map => M.lookup(eqString)('foo', map))
```

If it _was_ curried, you could write:

```ts
const pipeExample = pipe(m, M.lookup(eqString)('foo'))
```

Hope this helps!

**Comment by Melvillian** [comment]
Thank you, your reasoning behind `lookup` not being curried combined with re-reading https://mostly-adequate.gitbooks.io/mostly-adequate-guide/ch04.html#cant-live-if-livin-is-without-you helped clear this up. 

The reason I was trying to make it work with `pipe` was that many of the examples in `Map` use `pipe` so I figured that was the way to go.
