### ISSUE TITLE
Re-exporting the Record module creates a runtime exception

### ISSUE THREAD

**Issue by Magellol** [gcanti/fp-ts#1249]
### Current Behavior

We usually "extend" some modules with our own operators and we do this by re-exporting the module from another file such as:

```ts
// modules/Record/index.ts
export * from 'fp-ts/lib/Record';
export * from './operators';

// modules/Record/operators.ts
import * as R from 'fp-ts/lib/Record';

export const fn = () => {}
```

So in the codebase, we can do:

```ts
import * as R from 'modules/Record';

R.fn();
R.keys();
...
```

We've been doing that for different modules such as `Option`, `Array`, `Either` etc and all is good but for some reason re-exporting `Record` creates the following runtime exception

![image](https://user-images.githubusercontent.com/3819093/85442492-3a6d0d00-b55e-11ea-86f1-a2ea8fdbb06b.png)

### Expected behavior

No runtime exception. Allowing us to re-export the module to extend it.

### Your environment

| Software   | Version(s) |
| ---------- | ---------- |
| fp-ts      |           2.6.5 |
| TypeScript |            3.9.2|

**Comment by Magellol** [comment]
@OliverJAsh ran some tests and it may potentially be because of the following code generated by TS

```js
var __exportStar = (this && this.__exportStar) || function(m, exports) {
    for (var p in m) if (p !== "default" && !exports.hasOwnProperty(p)) __createBinding(exports, m, p);
}
```

https://www.typescriptlang.org/play/index.html?module=1&ssl=1&ssc=1&pln=1&pc=20#code/KYDwDg9gTgLgBAKjgMyhAtnA5MiEtA

In this case, it feels like the `export.hasOwnProperty` used by the snippet is pointing at the `hasOwnProperty` https://github.com/gcanti/fp-ts/blob/1b0ee81826e93ddd86ce20a3c353d349a6994bb6/src/ReadonlyRecord.ts#L162-L164

Looks like renaming it _should_ fix the issue

**Comment by gcanti** [comment]
@OliverJAsh RE: the "bug" label. It doesn't look `fp-ts`'s fault

**Comment by OliverJAsh** [comment]
Yeah you're right. Although the TS team have already said they won't fix this, so I guess it's on us to workaround it instead? https://github.com/microsoft/TypeScript/issues/3197#issuecomment-103071613

**Comment by gcanti** [comment]
> the TS team have already said they won't fix this

I see. I can't rename `hasOwnProperty` because would be a breaking change.

However, as a fix, I can try to handle `this`

```ts
const _hasOwnProperty = Object.prototype.hasOwnProperty

export function hasOwnProperty<K extends string>(k: string, r: ReadonlyRecord<K, unknown>): k is K
export function hasOwnProperty<K extends string>(this: any, k: string, r?: ReadonlyRecord<K, unknown>): k is K {
  return _hasOwnProperty.call(r === undefined ? this : r, k)
}
```

what do you think?

**Comment by OliverJAsh** [comment]
That should work!

**Comment by OliverJAsh** [comment]
This bug is happening again in 2.10.0 when we try to call `Record.filterMap`. It looks like it's because of this change: https://github.com/gcanti/fp-ts/commit/02e0d218d868657cc95b95ba0056b40286756b78#diff-2a28f9bcbc06ac11c7768967193244d8f9ca05a4e96225ca8449930aa26870b0R663.

We need to apply the same fix to `hasOwnProperty ` here:

https://github.com/gcanti/fp-ts/blob/6a38637b9ebb7db1e29424f7f7255fc488d1d88e/src/internal.ts#L28

I'll raise a PR.

**Comment by gcanti** [comment]
@OliverJAsh damn, I forgot again this issue, I'm sorry :(

This is an internal function so we can rename it (to `has` for example) without any worries

**Comment by OliverJAsh** [comment]
Unfortunately the issue persists in 2.10.1. I think this change is also causing an issue: https://github.com/gcanti/fp-ts/commit/281dc29a351cf719d11d2458f5b69b5e5471a1bf#diff-dc4b4fb0cd6e06c8bf587eb2f8817ffa1ed096efe2c6c5175d3604fb57d3a96cR796

`Record.hasOwnProperty` no longer handles `this` because it's now just an alias for `RR.has`, and `RR.has` doesn't handle `this` anymore: https://github.com/gcanti/fp-ts/commit/281dc29a351cf719d11d2458f5b69b5e5471a1bf#diff-2a28f9bcbc06ac11c7768967193244d8f9ca05a4e96225ca8449930aa26870b0L168

I'm not sure how we should fix this. WDYT @gcanti?
