### ISSUE TITLE
Proposal: better signature of equal method

### ISSUE THREAD

**Issue by Wenqer** [gcanti/fp-ts#130]
Hello @gcanti, thanks for the cool library!

I want to use it, but there is one ideological thing that does not arrange me.

In the Option (and other monads which implement the setoid) equals method takes the first parameter as Setoid (https://github.com/gcanti/fp-ts/blob/master/src/Option.ts#L81) and a second parameter is what we want to compare.
Accordingly, in all calls, we need to pass there setoid explicitly.

Is it possible to make setoid as second and optional param and add a possibility to set a default value from the constructor of the monad?

This will help us get rid of the transfer one parameter in each equals method and will support a more traditional interface of the equals method.

**Comment by gcanti** [comment]
This is due to the straightforward way to translate instances from PureScript to fp-ts

```purescript
-- Eq is the same as Setoid
derive instance eqMaybe :: Eq a => Eq (Maybe a)
```

where type parameter constraints are translated to additional first parameters in the shape of dicitonaries

```ts
export function getSetoid<A>(setoid: Setoid<A> /* <- this is the counterpart of Eq a => */): Setoid<Option<A>> {
  return {
    equals: (x, y) => equals(setoid, x, y)
  }
}
```

and it's consistent through the whole library.

We could say the same for `Option.concat`

PureScript

```purescript
instance semigroupMaybe :: Semigroup a => Semigroup (Maybe a) where
  ...
```

fp-ts

```ts
export function getSemigroup<A>(semigroup: Semigroup<A>): Semigroup<Option<A>> {
  return { concat: (fx, fy) => concat(semigroup, fx, fy) }
}
```

You could just curry `equals` (https://github.com/gcanti/fp-ts/issues/131)
