### ISSUE TITLE
await in function that returns task (possibly wrong approach)

### ISSUE THREAD

**Issue by Matthijn** [gcanti/fp-ts#1483]
I'm quite new on trying functional programming, so, possibly I'm doing this completely wrong. Butt a Task is defined as. 

```Task<A> represents an asynchronous computation that yields a value of type A and never fails. ```

Which minus the 'never fails part' seems like a promise to me. So I have the following code.

```
export async function storeJob(job: CreateJob): Task<Job> {
  const createDto = toCreateDto(job)
  const query = createInsertQuery('jobs', createDto)
  await pool.query(query)
  return fromDto(createDto)
}
```

But an async function needs to return a promise. So do I then do `Promise<Task<Job>>` that seems not quite correct to me. Perhaps I have to call my functions differently. So, could someone then push me in the right direction on how I could refactor this so I can still use a promise based library (`pool.query`) in this case to do the actual work? (Storing contents in the database in this case). 

A related question, would this be an TaskEither instead? Basically, I have already validated the `job` extensively. So, the `createDto`, `createInserQuery` and `fromDto` are pure functions. So the only thing that could fail is that if the database connection fails. Is that a kind of failure I will have tot check for each time? (Eg when db connection is broken, nothing will  work anyway, there's not really a recover scenario there).

**Comment by DenisFrezzato** [comment]
This is the type of a `Task<A>`, [from the documentation](https://gcanti.github.io/fp-ts/modules/Task.ts.html#task-interface):
```ts
interface Task<A> {
  (): Promise<A>
}
```
so it's not _like a promise_, it's a thunk that returns a promise.

Now, to your example, I suggest you to wrap `pool.query` into a `TaskEither`:
```ts
import * as TE from 'fp-ts/TaskEither'

type DBError = { _tag: 'SomeException', exception: Error } | // ...
declare const someException: (e: Error) => DBError
declare const toDBError: (u: unknown) => DBError

export const query: (sql: string): TE.TaskEither<DBError, unknown> = 
  TE.tryCatch(() => pool.query(sql), toDBError)
```

The `storeJob` function:
```ts
export function storeJob(job: CreateJob): TE.TaskEither<DBError, Job> {
  const createDto = toCreateDto(job)
  const sql = createInsertQuery('jobs', createDto)
  return pipe(
    query(sql),
    TE.map(() => fromDto(createDto))
  )
}
```
Finally, at the boundaries, you run the effect:
```ts
const storeAJob = pipe(
  storeJob(myJob),
  TE.getOrElse(...) // You may want to handle the error here
)
storeJob() // Promise<Job>
```

> So the only thing that could fail is that if the database connection fails.

This is one thing, but there are others. For example it can fail also because of an invalid query or the data you're trying to insert are rejected by the database for some reason.

> Is that a kind of failure I will have tot check for each time?

This is up to you and your team. I handle any error that may occur, modeling different types of errors, from generic errors for you abstraction layer to specific for the domain (like decoding failure, one for any error that might be thrown by the effect, that is the aforementioned `SomeException` member, or a not found resource, invalid request...).

**Comment by Matthijn** [comment]
Awesome, thanks, that clears a bunch of things up.
