### ISSUE TITLE
Set structure?

### ISSUE THREAD

**Issue by justinwoo** [gcanti/fp-ts#161]
I was wondering since you have a StrMap in here if you planned to add a Set or could point me to an implementation that works well enough and is well-typed

**Comment by SimonMeskens** [comment]
Immutable.js has a Set implementation that's very well-typed and mostly fantasy-land compliant. I'm working on making it fully fantasy- and static-land compliant and integrated with fp-ts, but you can mostly just start using it.

Most of the implementations in fp-ts are naive, so for heavy duty collections, you're usually better off with one of the Clojure style implementations anyway.

[Immutable.js](https://facebook.github.io/immutable-js/) (really good types)
[Mori](http://swannodette.github.io/mori/) (more functional, no types)

**Comment by justinwoo** [comment]
I've had a really bad time with using Immutable.js in any context, so I'll be looking forward to seeing your compatibility layer sometime

**Comment by SimonMeskens** [comment]
Oh really? If you tell me some of the issues you had, I could look into improving some of them in the compatibility layer.

**Comment by SimonMeskens** [comment]
I'm basically giving up on both Immutable.js and Mori. I invested about 100 hours into getting Immutable.js to play nice, but I'm getting consistent TypeScript compiler crashes at this point, it's just not worth it. There's an insane amount of bugs related to Immutable.js that just make it unworkable.

Mori has been abandoned basically, so that's a no-go too.

I'm currently looking into [Collectable.js](https://github.com/frptools/collectable) as an alternative. It seems to align way more with the spirit of functional programming and open source than the other two, so I'm hopeful.

I also realized that a naive Set implementation might be a benefit to fp-ts, so I'll try to make some time to provide one.

**Comment by tycho01** [comment]
Speaking of native, you'll have the [ES6 one](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set) for reference as well!

**Comment by SimonMeskens** [comment]
I've been mulling this one over and I think the best course of action is two-fold:

One, give ES6 Sets the same treatment we give to Arrays, so there's a well-typed Set available.
Two, implement lattices (as well as join- and meet-semilattices). Set would be a join-semilattice, but not a lattice I think.

Lattices are cool abstractions that are often forgotten for some reason. They're like monads for idempotent operations. I think figuring out how they work might give us some cool new toys for fp-ts.

Tree operations tend to be semilattices too IIRC

**Comment by gcanti** [comment]
> Set would be a join-semilattice, but not a lattice I think.

@SimonMeskens if `Set<A>` represents the collection of all subsets of `A` (i.e. the *power set* of `A`) then is a lattice with respect to intersection (meet) and union (join)

**Comment by SimonMeskens** [comment]
Ah okay, I see now. I'll have to make some time in my schedule to write this module.
