### ISSUE TITLE
array map not curried

### ISSUE THREAD

**Issue by leemhenson** [gcanti/fp-ts#235]
Was that a deliberate choice or simply an oversight?

https://github.com/gcanti/fp-ts/blob/master/src/Array.ts#L43

**Comment by gcanti** [comment]
It's a deliberate choice in order to be compatibile with Functor's map https://github.com/gcanti/fp-ts/blob/6e33d68aa493c654502dd6b0dcda18e448369ed0/src/Functor.ts#L6 which in turn is not curried to get better type inference when you build programs abstracted over a typeclass like this one https://github.com/gcanti/fp-ts/blob/6e33d68aa493c654502dd6b0dcda18e448369ed0/examples/mtl.ts#L23

**Comment by leemhenson** [comment]
Ok, thanks.
