### ISSUE TITLE
add Tree module

### ISSUE THREAD

**Issue by gcanti** [gcanti/fp-ts#26]
Where

```purescript
data BinaryTree a = Empty | Node a (Tree a) (Tree a)

```

- Monad
- Foldable
- Traversable

**Comment by rilut** [comment]
Hi, I'm trying to implement BinaryTree in https://github.com/rilut/fp-ts/blob/add-binarytree/src/BinaryTree.ts. It's still WIP though.

So far, my inspiration is from https://gist.github.com/schmmd/1271891 & https://gist.github.com/dholbrook/2967371. Because both implementations have different style, I plan to stick to one of them.  
I see you referenced a Purescript signature above, but sorry I'm still not really familiar with them.

My questions are:
- what classes/methods I should keep?
- is `Empty`==`None`?
- how `traverse` method fits with preorder/inorder/postorder?
- do we need `Leaf` class? or is `Node` just enough?
- do we need covariance in this `Tree`? but how to do it in TypeScript?

Thanks!

**Comment by gcanti** [comment]
```purescript
data BinaryTree a = Empty | Node a (Tree a) (Tree a)
```

is an `ADT` (algebraic data type) and can be roughly translated to

```ts
export type Tree<A> = Empty | Node<A>
export class Empty {}
export class Node<A> {
  constructor(
    public readonly left: Tree<A>,
    public readonly value: A,
    public readonly right: Tree<A>
  ) {}
}
```

however, due to a [known limitation of TypeScript](https://github.com/Microsoft/TypeScript/issues/16032#issuecomment-303470726), if we want to implement `map`, `ap`, `chain` etc.. methods on them we must ensure the same signature, so we have to add a fake type parameter to `Empty` as well

```ts
export type Tree<A> = Empty<A> | Node<A>
export class Empty<A> {
  map<B>(f: (a: A) => B): Tree<B> { // this signature must be equal to...
    ...
  }
}
export class Node<A> {
  constructor(
    public readonly left: Tree<A>,
    public readonly value: A,
    public readonly right: Tree<A>
  ) {}
  map<B>(f: (a: A) => B): Tree<B> { // ...this!
    ...
  }
}
```

Since we need only an instance of `Empty` we could implement the singleton pattern making the constructor private

```ts
export type Tree<A> = Empty<A> | Node<A>

export class Empty<A> {
  static value: Tree<any> = new Empty() // <= note the `any` here
  private constructor() { }
  map<B>(f: (a: A) => B): Tree<B> {
    ...
  }
}

export empty = Empty.empty

export class Node<A> {
  constructor(
    public readonly left: Tree<A>,
    public readonly value: A,
    public readonly right: Tree<A>
  ) {}
  map<B>(f: (a: A) => B): Tree<B> {
    ...
  }
}
```

> do we need covariance in this Tree? but how to do it in TypeScript?

We can't, TypeScript doesn't support variance annotations. This explains the `any` in the snippet above.

> what classes/methods I should keep?

It's up to you, if you think that a function will be generally useful, feel free to add it

> how traverse method fits with preorder/inorder/postorder?

You can define and export all of them: `Tree` can have multiple instance of `Traversable` (it's the beauty of static-land)

**Comment by rilut** [comment]
Hi, is `traverse` ever used in fp-ts?
