### ISSUE TITLE
Add Flow support

### ISSUE THREAD

**Issue by gcanti** [gcanti/fp-ts#275]
I'm working (branch `flow`) on a definition file (actually shadow files) based on this HKT encoding https://twitter.com/hallettj/status/932674096659419143 by @hallettj

**Comment by volkanunsal** [comment]
It would be amazing if this allows us to use this library without switching to TypeScript.

**Comment by gcanti** [comment]
@volkanunsal I'm working hard to make it happen ;)

Need some help for testing out though, it is now almost a year since I switched to TypeScript, I'm a bit rusty at Flow

**Comment by raveclassic** [comment]
Great initiative! 
What about maintenance though? Should we now duplicate new features in both languages and what about flow tricks TS doesn't even support now? 
Maybe a better way is to publish separate lib `fp-flow`? Such that could also support do-notation via generators as flow supports them correctly.

**Comment by gcanti** [comment]
The PR is here https://github.com/gcanti/fp-ts/pull/276

You can try it out running `fp-ts@next`. 

All modules are there but please keep in mind that is an alpha.

Example

```js
// @flow

import { array } from 'fp-ts/lib/Array'
import { sequence } from 'fp-ts/lib/Traversable'
import { some, none, option } from 'fp-ts/lib/Option'

console.log(sequence(option, array)([some(1), some(2)])) // some([1, 2])
console.log(sequence(option, array)([none, some(2)])) // none
```

@raveclassic This is experimental, let's see how it goes. I'm not even sure it will work out well at the moment.

**Comment by gcanti** [comment]
fixed some issues with type parameters order and published a new version

**Comment by gcanti** [comment]
> I'm not even sure it will work out well at the moment

It works pretty well! Even the advanced features. Some more examples:

- Free Monad: https://gist.github.com/gcanti/087a190fe0090210b82939f4bf3a1531
- Monad transformers: https://gist.github.com/gcanti/56896de8716604e3f8a75edc27f550c4
- MTL-style: https://gist.github.com/gcanti/10c8e1b3bb4b759681f8014b4cd7f820

**Comment by zerobias** [comment]
Things in flow that are worth a look:

 - $Call type
```js
const result: B = $Call<A => B, A>
```

 - Phantom types (yes, officially)
https://github.com/facebook/flow/commit/e4b2c0590a81bdd1a2726708c6fe3f75cd9de839

 - Opaque types with type constraints
https://medium.com/flow-type/hiding-implementation-details-with-flows-new-opaque-type-aliases-feature-40e188c2a3f9
Really powerful way to denote new types

 - $ReadOnly type
Make every field covariant

 - $Rest type
opposed to $Diff

 - empty type
Similar to `never` in ts

 - $NonMaybeType obvious

 - $ReadOnlyArray<+T> useful as function argument (covariant makes flow's work easier)

 - $Compose (native support for typical compose function)

 - Well-known $Keys now can return string literal's union instead of just string
And got $Values with similar behavior

 - And pretty useful comments syntax
flow thinks about code in /*:: */ as if it was real code
```js
// types.js
opaque type UserID: number = number
declare export function toUserID(userid: number): UserID

// usage.js
/*::
import { toUserID } from './types'
*/
function usersInJson(users: $ReadOnlyArray<{ id: number }>) {
  return users
    .map(user => user.id )
/*::.map( toUserID ) */
}
```

**Comment by gcanti** [comment]
https://github.com/gcanti/fp-ts/releases/tag/0.6.4
