### ISSUE TITLE
how to use your doc to learn

### ISSUE THREAD

**Issue by baldegit** [gcanti/fp-ts#564]
Hello,
I am currently learning the fp-ts, and I find your repository.
But after reading your readme, I am a little lost, I can not know where to start and I downloaded the project but I do not know what to do with it. Do you have advice for me ??

Thank you in advance

**Comment by gcanti** [comment]
Docs only contain the API reference and some examples, so in order to use this library you are supposed to have a basic understanding of functional programming patterns and a basic knowledge of the most common data types and type classes.

A couple of introductory resources on functional programming

- Fantas, Eel, and Specification (JavaScript) http://www.tomharding.me/2017/03/03/fantas-eel-and-specification/
- Mostly adequate guide to FP (JavaScript) https://github.com/MostlyAdequate/mostly-adequate-guide
- FP list combinators demo with fp-ts (TypeScript) https://twitter.com/OliverJAsh/status/1035559910170402816
- Jargon from the functional programming world in simple terms https://github.com/hemanth/functional-programming-jargon

I also wrote a free book, an introduction to functional programming, unfortunately is in italian (*) https://github.com/gcanti/functional-programming

(*) by the way if someone is willing to help me with the english translation, please let me know, I don't have the bandwidth to start a translation (and besides, my english is pretty ugly...)

**Comment by baldegit** [comment]
Thank you for your answer . I will visit the url s you proposed. thank you
