### ISSUE TITLE
Tsc crash when mixing fp-ts/lib & fp-ts/es6

### ISSUE THREAD

**Issue by jollytoad** [gcanti/fp-ts#860]
**Do you want to request a _feature_ or report a _bug_?**

bug

**What is the current behavior?**

If I import a module from fp-ts/es6 and also another module that indirectly imports the same module but from fp-ts/lib, the tsc compiler goes crazy and eventually crashes with a heap allocation failure (often after several minutes).

I've found this when using both io-ts and fp-ts-rxjs.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://codesandbox.io/ or similar.**

```
import {observable} from 'fp-ts-rxjs/lib/Observable'
import {right} from 'fp-ts/es6/Either'
```

**What is the expected behavior?**

not to crash!

**Which versions of fp-ts, and which browser and OS are affected by this issue? Did this work in previous versions of fp-ts?**

fp-ts: 1.17.3
fp-ts-rxjs: 0.5.1
io-ts: 1.8.5

**Comment by jollytoad** [comment]
I think i may have found a work-around, by setting a path in the tsconfig...
```
"fp-ts/lib/*": [ "node_modules/fp-ts/es6/*" ]
```
I'll see how it goes with this and report back.

**Comment by jollytoad** [comment]
So, i can confirm this fixes all the crashes i had when mixing io-ts or fp-ts-rxjs with fp-ts/es6 modules.

Maybe it's something that could be added to the caveats of the es6 module usage in case anyone hits the problem.

Oh, and on the issue of es6 caveats, regarding jest, you need to add the follow jest config...

```
    "transformIgnorePatterns": [
      "<rootDir>/node_modules/(?!(fp-ts/es6)/)"
    ],
```

**Comment by wmaurer** [comment]
@jollytoad Thanks for your `tsconfig.json` work-around (`"fp-ts/lib/*": [ "node_modules/fp-ts/es6/*" ]`). 

This in fact, fixes much more than the tsc crashing that you experienced. In my app which uses webpack to bundle, it also fixes inconsistencies which otherwise end up in the bundle!

For example, if I have a project that uses `io-ts`, and I import from `io-ts/es6` and call the `decode` method on a runtime type, I get an `Either` return type. When I analyse this with `webpack-bundle-analyzer`, I see this (io-ts v1):

![image](https://user-images.githubusercontent.com/2899448/60547541-4265e880-9d20-11e9-8410-02a9f8eb5590.png)

Ouch! I'm importing from `io-ts/es6` but am getting `fp-ts/lib` in the bundle. After your fix, I see 

![image](https://user-images.githubusercontent.com/2899448/60547679-9b358100-9d20-11e9-8a85-3e56928a81dd.png)

Much better!

Similar with io-ts v2. Before:
![image](https://user-images.githubusercontent.com/2899448/60547750-c28c4e00-9d20-11e9-98e9-331c0ab562e4.png)

After:

![image](https://user-images.githubusercontent.com/2899448/60547776-d59f1e00-9d20-11e9-988d-5171b5640425.png)

Also much better!

This says to me that something is somewhere wrong with the es6 bundling in the `fp-ts` ecosystem, but at this moment I've no idea how it can be resolved. All I know is that if I import from `io-ts/es6`, I'd ideally like `fp-ts/es6` in my bundle.

Your work-around works well enough for me though ;-)

**Comment by jjm340** [comment]
> So, i can confirm this fixes all the crashes i had when mixing io-ts or fp-ts-rxjs with fp-ts/es6 modules.
> 
> Maybe it's something that could be added to the caveats of the es6 module usage in case anyone hits the problem.
> 
> Oh, and on the issue of es6 caveats, regarding jest, you need to add the follow jest config...
> 
> ```
>     "transformIgnorePatterns": [
>       "<rootDir>/node_modules/(?!(fp-ts/es6)/)"
>     ],
> ```

Thanks a ton for this, was pulling my hair out trying to get this to work with jest!
