### ISSUE TITLE
Incorrect generics on TaskEither.d.ts

### ISSUE THREAD

**Issue by nthypes** [gcanti/fp-ts#939]
### Current Behavior

After upgrade to version `2.0.4` or `2.0.5` we got an error in compilation on TypeScript.

### Expected behavior

Compile our project cleanly.

### Suggested solution(s)

Adjust the generics types of `lib/TaskEither.d.ts`

### Additional context

https://unpkg.com/fp-ts@2.0.3/lib/TaskEither.d.ts
https://unpkg.com/fp-ts@2.0.4/lib/TaskEither.d.ts

Check the diffs of the lines **154 & 157**.

ERROR:

```
error TS2742: The inferred type of 'tryOrThrow' cannot be named without a reference to 'internal-pkg/node_modules/.registry.npmjs.org/fp-ts/2.0.5/node_modules/fp-ts/lib/TaskEither'. This is likely not portable. A type annotation is necessary.
```

### Your environment

Which versions of fp-ts are affected by this issue? Did this work in previous versions of fp-ts?

| Software   | Version(s) |
| ---------- | ---------- |
| fp-ts      |    2.0.4        |
| TypeScript |   3.5.3         |
| pnpm | 3.5.6 |

**Comment by giogonzo** [comment]
I don't see anything wrong with the generated `.d.ts` per se - I think this is an issue in your own project/build setup.

`TS2742` means you have `declaration: true` in your `tsconfig.json` but TS cannot generate the complete d.ts output since the `tryOrThrow` signature (your project code) would reference some external types (`TaskEither`) that are not already imported in your file.

You'll need to add an import of the missing types in your source code to fix the issue. This gets particularly annoying with `noUnusedImports: true` since you'll now get a warning for the unused imported type, I usually just `@ts-ignore` the import line in these cases.

**Comment by nthypes** [comment]
Agree 100% with you. It was a misinterpretation at my side. 

I'm closing this.
