### ISSUE TITLE
Question: Type alias vs Interfaces

### ISSUE THREAD

**Issue by EricHenry** [gcanti/fp-ts#953]
Hey!

Love the project and all the work you all have done on it. Just wanted to leave some appreciation for everyone on the project. 

I also have a question about how you are implementing your modules in TS. I am looking for some insight about how to determine whether to use `interface`s vs `type`s. 

Looking at the `Option` module there seem to be some deliberate reasoning on how you decide which to use, I am not too confident on my understanding of them. As an example, `Some` and `None` are interfaces but `Option` is a type. Is that because `Some` and `None` hold on to some data, but `Option` doesn't. Instead `Option` describes the two variants `Some` and `None` so using a union type makes more sense?

Assuming the above is correct, do you guys recommend this approach to writing TypeScript generally?

Thanks!
Eric

**Comment by grossbart** [comment]
I think the decision is mainly based around the [tslint interface-over-type-literal rule](https://palantir.github.io/tslint/rules/interface-over-type-literal/). There is some reasoning behind the existence of this rule (see this [discussion](https://stackoverflow.com/questions/37233735/typescript-interfaces-vs-types) and many others) and there are cases where it does matter whether you pick one or the other, but in most cases it's mostly "pick an interface unless you need a type".

What interfaces can't express is sum types / tagged unions like `type Option<A> = None | Some<A>`, so in this situation you need a `type`.

On the other hand, when you create a type alias it's beneficial to use an interface because your editor will be able to show the intended name and not the name of the primitive. Here's an example:

<img width="244" alt="type" src="https://user-images.githubusercontent.com/10811/65368742-6cef7f80-dc45-11e9-92fa-fbb9b55ff7b1.png">
<img width="244" alt="interface" src="https://user-images.githubusercontent.com/10811/65368745-6fea7000-dc45-11e9-81ca-d4074d7c144b.png">

**Comment by EricHenry** [comment]
Thanks, appreciate the feedback!
