### ISSUE TITLE
FunctionN

### ISSUE THREAD

**Issue by steida** [gcanti/fp-ts#992]
## 📖 Documentation

It seems it's very handy. Why it is not used everywhere? And it could be named just FN.

**Comment by steida** [comment]
@raveclassic Care to comment? Do you know why it exists?

**Comment by raveclassic** [comment]
@steida Why would you ever need an alias for a function? TypeScript is not Haskell, it requires argument names in function declarations and _personally_ I don't see any valid reasons for replacing a native language construction with a handmade alias. Otherwise readability suffers and maintenance complexity increases. IMO.
